import {
  Employee,
  UserRole,
  AttendanceStatus,
  EmploymentStatus,
  Attendance,
  LeaveRequest,
  LeaveType,
  LeaveStatus,
  SalaryStructure,
  WageType,
  Skill,
  Certification,
} from "../types";

export const mockEmployees: Employee[] = [
  {
    id: "1",
    employeeId: "EMP-001",
    loginId: "OIJACO20210001",
    firstName: "Jane",
    lastName: "Cooper",
    fullName: "Jane Cooper",
    email: "jane.cooper@company.com",
    personalEmail: "jane.cooper@gmail.com",
    phone: "+1 (555) 123-4567",
    personalPhone: "+1 (555) 987-6543",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    role: UserRole.EMPLOYEE,
    jobTitle: "UI/UX Designer",
    department: "Design",
    location: "New York",
    manager: "Sarah Connor",
    dateOfBirth: "1990-05-15",
    gender: "Female",
    maritalStatus: "Single",
    nationality: "American",
    dateOfJoining: "2021-03-15",
    yearOfJoining: 2021,
    serialNumber: 1,
    employmentStatus: EmploymentStatus.ACTIVE,
    workLocation: "New York Office",
    permanentAddress: "123 Main St, New York, NY 10001",
    emergencyContactName: "John Cooper",
    emergencyContactPhone: "+1 (555) 111-2222",
    status: AttendanceStatus.PRESENT,
    checkInTime: "09:00 AM",
    companyCode: "OI",
  },
  {
    id: "2",
    employeeId: "EMP-024",
    loginId: "OICOFI20200024",
    firstName: "Cody",
    lastName: "Fisher",
    fullName: "Cody Fisher",
    email: "cody.fisher@company.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Cody",
    role: UserRole.EMPLOYEE,
    jobTitle: "Software Engineer",
    department: "Engineering",
    location: "Remote",
    manager: "Tech Lead",
    dateOfJoining: "2020-06-10",
    yearOfJoining: 2020,
    serialNumber: 24,
    employmentStatus: EmploymentStatus.ON_LEAVE,
    status: AttendanceStatus.LEAVE,
    companyCode: "OI",
  },
  {
    id: "3",
    employeeId: "EMP-045",
    loginId: "OIESHO20190045",
    firstName: "Esther",
    lastName: "Howard",
    fullName: "Esther Howard",
    email: "esther.howard@company.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Esther",
    role: UserRole.EMPLOYEE,
    jobTitle: "Project Manager",
    department: "Management",
    location: "London",
    dateOfJoining: "2019-01-20",
    yearOfJoining: 2019,
    serialNumber: 45,
    employmentStatus: EmploymentStatus.ACTIVE,
    status: AttendanceStatus.ABSENT,
    companyCode: "OI",
  },
  {
    id: "4",
    employeeId: "EMP-088",
    loginId: "OIJEWI20200088",
    firstName: "Jenny",
    lastName: "Wilson",
    fullName: "Jenny Wilson",
    email: "jenny.wilson@company.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jenny",
    role: UserRole.HR,
    jobTitle: "HR Associate",
    department: "Human Resources",
    location: "New York",
    dateOfJoining: "2020-08-12",
    yearOfJoining: 2020,
    serialNumber: 88,
    employmentStatus: EmploymentStatus.ACTIVE,
    status: AttendanceStatus.PRESENT,
    checkInTime: "08:45 AM",
    companyCode: "OI",
  },
  {
    id: "5",
    employeeId: "EMP-092",
    loginId: "OIALFL20210092",
    firstName: "Albert",
    lastName: "Flores",
    fullName: "Albert Flores",
    email: "albert.flores@company.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Albert",
    role: UserRole.EMPLOYEE,
    jobTitle: "Backend Developer",
    department: "Engineering",
    location: "Remote",
    dateOfJoining: "2021-09-05",
    yearOfJoining: 2021,
    serialNumber: 92,
    employmentStatus: EmploymentStatus.ACTIVE,
    status: AttendanceStatus.PRESENT,
    checkInTime: "09:15 AM",
    companyCode: "OI",
  },
  {
    id: "6",
    employeeId: "EMP-033",
    loginId: "OIMAMC20180033",
    firstName: "Marvin",
    lastName: "McKinney",
    fullName: "Marvin McKinney",
    email: "marvin.mckinney@company.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marvin",
    role: UserRole.EMPLOYEE,
    jobTitle: "Product Owner",
    department: "Product",
    location: "Berlin",
    dateOfJoining: "2018-11-30",
    yearOfJoining: 2018,
    serialNumber: 33,
    employmentStatus: EmploymentStatus.ACTIVE,
    status: AttendanceStatus.LEAVE,
    companyCode: "OI",
  },
  {
    id: "7",
    employeeId: "EMP-076",
    loginId: "OIROFO20200076",
    firstName: "Robert",
    lastName: "Fox",
    fullName: "Robert Fox",
    email: "robert.fox@company.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Robert",
    role: UserRole.EMPLOYEE,
    jobTitle: "Full Stack Dev",
    department: "Engineering",
    location: "London",
    dateOfJoining: "2020-02-14",
    yearOfJoining: 2020,
    serialNumber: 76,
    employmentStatus: EmploymentStatus.ACTIVE,
    status: AttendanceStatus.PRESENT,
    checkInTime: "08:55 AM",
    companyCode: "OI",
  },
  {
    id: "8",
    employeeId: "EMP-012",
    loginId: "OIKRWA20210012",
    firstName: "Kristin",
    lastName: "Watson",
    fullName: "Kristin Watson",
    email: "kristin.watson@company.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kristin",
    role: UserRole.EMPLOYEE,
    jobTitle: "QA Tester",
    department: "Quality Assurance",
    location: "New York",
    dateOfJoining: "2021-07-22",
    yearOfJoining: 2021,
    serialNumber: 12,
    employmentStatus: EmploymentStatus.ACTIVE,
    status: AttendanceStatus.ABSENT,
    companyCode: "OI",
  },
];

export const mockAttendance: Attendance[] = [
  {
    id: "1",
    employeeId: "EMP-001",
    employeeName: "Jane Cooper",
    date: "2023-10-26",
    checkIn: "09:00 AM",
    checkOut: "06:00 PM",
    workHours: "9h 00m",
    status: AttendanceStatus.PRESENT,
    department: "Engineering",
  },
  {
    id: "2",
    employeeId: "EMP-001",
    employeeName: "Jane Cooper",
    date: "2023-10-25",
    checkIn: "08:55 AM",
    checkOut: "06:05 PM",
    workHours: "9h 10m",
    status: AttendanceStatus.PRESENT,
    department: "Engineering",
  },
  {
    id: "3",
    employeeId: "EMP-001",
    employeeName: "Jane Cooper",
    date: "2023-10-24",
    checkIn: "09:45 AM",
    checkOut: "06:15 PM",
    workHours: "8h 30m",
    status: AttendanceStatus.LATE,
    note: "Traffic Delay",
    department: "Engineering",
  },
  {
    id: "4",
    employeeId: "EMP-001",
    employeeName: "Jane Cooper",
    date: "2023-10-23",
    checkIn: "09:02 AM",
    checkOut: "06:00 PM",
    workHours: "8h 58m",
    status: AttendanceStatus.PRESENT,
    department: "Engineering",
  },
  {
    id: "5",
    employeeId: "EMP-001",
    employeeName: "Jane Cooper",
    date: "2023-10-22",
    status: AttendanceStatus.WEEKEND,
    note: "Sunday",
    department: "Engineering",
  },
  {
    id: "6",
    employeeId: "EMP-004",
    employeeName: "Cody Fisher",
    date: "2023-10-24",
    checkIn: "09:15 AM",
    status: AttendanceStatus.PRESENT,
    department: "Design",
  },
  {
    id: "7",
    employeeId: "EMP-012",
    employeeName: "Esther Howard",
    date: "2023-10-24",
    checkIn: "08:55 AM",
    checkOut: "06:05 PM",
    workHours: "9h 10m",
    status: AttendanceStatus.PRESENT,
    department: "Marketing",
  },
  {
    id: "8",
    employeeId: "EMP-023",
    employeeName: "Jenny Wilson",
    date: "2023-10-24",
    status: AttendanceStatus.LEAVE,
    workHours: "0h 00m",
    department: "Human Resources",
  },
  {
    id: "9",
    employeeId: "EMP-015",
    employeeName: "Adam Smith",
    date: "2023-10-24",
    checkIn: "10:30 AM",
    status: AttendanceStatus.LATE,
    department: "Engineering",
  },
];

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: "1",
    employeeId: "EMP001",
    employeeName: "Emp Name",
    type: LeaveType.PAID,
    startDate: "2023-10-28",
    endDate: "2023-10-30",
    duration: 3,
    reason: "Family vacation",
    status: LeaveStatus.PENDING,
    appliedDate: "2023-10-20",
  },
  {
    id: "2",
    employeeId: "EMP042",
    employeeName: "John Smith",
    type: LeaveType.SICK,
    startDate: "2023-10-25",
    endDate: "2023-10-25",
    duration: 1,
    reason: "Medical appointment",
    status: LeaveStatus.APPROVED,
    appliedDate: "2023-10-24",
    reviewedBy: "HR Manager",
    reviewedDate: "2023-10-24",
  },
  {
    id: "3",
    employeeId: "EMP089",
    employeeName: "Alice Liu",
    type: LeaveType.UNPAID,
    startDate: "2023-11-01",
    endDate: "2023-11-05",
    duration: 5,
    reason: "Personal matters",
    status: LeaveStatus.PENDING,
    appliedDate: "2023-10-22",
  },
];

export const mockSalaryStructure: SalaryStructure = {
  basicSalary: 2500,
  currency: "USD",
  wageType: WageType.FIXED,
  earnings: [
    {
      id: "1",
      name: "House Rent Allowance (HRA)",
      amount: 1000,
      type: "EARNING",
      description: "Calculated as % of basic salary",
      isPercentage: true,
      percentage: 40,
    },
    {
      id: "2",
      name: "Standard Allowance",
      amount: 800,
      type: "EARNING",
      description: "Fixed monthly amount",
    },
    {
      id: "3",
      name: "Performance Bonus",
      amount: 500,
      type: "EARNING",
      description: "Variable based on quarterly reviews",
    },
  ],
  deductions: [
    {
      id: "1",
      name: "Provident Fund (PF)",
      amount: 300,
      type: "DEDUCTION",
      description: "Employee Contribution",
      isPercentage: true,
      percentage: 12,
    },
    {
      id: "2",
      name: "Professional Tax",
      amount: 200,
      type: "DEDUCTION",
      description: "Fixed state tax",
    },
  ],
  grossSalary: 4800,
  netSalary: 4300,
  workingDays: 5,
};

export const mockSkills: Skill[] = [
  { name: "JavaScript (React, Node)", level: 90 },
  { name: "Python (Django)", level: 75 },
  { name: "SQL / Database Design", level: 85 },
  { name: "UI/UX Basics", level: 60 },
];

export const mockCertifications: Certification[] = [
  {
    name: "AWS Certified Solutions Architect",
    issuer: "Amazon Web Services",
    issueDate: "Jan 2023",
  },
  {
    name: "Professional Scrum Master I",
    issuer: "Scrum.org",
    issueDate: "Nov 2022",
  },
];

export const currentEmployee: Employee = {
  id: "100",
  employeeId: "EMP00451",
  loginId: "OIJODO20210451",
  firstName: "John",
  lastName: "Doe",
  fullName: "John Doe",
  email: "johndoe@example.com",
  personalEmail: "john.doe.personal@gmail.com",
  phone: "+1 (555) 123-4567",
  personalPhone: "+1 (555) 987-6543",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=JohnDoe",
  role: UserRole.EMPLOYEE,
  jobTitle: "Senior Software Engineer",
  department: "Engineering",
  location: "New York, NY",
  manager: "Sarah Connor",
  dateOfBirth: "1990-08-15",
  gender: "Male",
  maritalStatus: "Single",
  nationality: "United States",
  dateOfJoining: "2021-03-01",
  yearOfJoining: 2021,
  serialNumber: 451,
  employmentStatus: EmploymentStatus.ACTIVE,
  workLocation: "Headquarters - New York",
  permanentAddress: "123 Maple Avenue, Apt 4B, Springfield, IL 62704",
  emergencyContactName: "Sarah Morgan",
  emergencyContactPhone: "+1 (555) 111-2222",
  status: AttendanceStatus.PRESENT,
  checkInTime: "09:00 AM",
  companyCode: "OI",
};
